name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image with secrets
        run: |
          docker build . -f Dockerfile -t my-image-name:$(date +%s) \
            --build-arg MONGODB_URI=${{ secrets.MONGODB_URI }} \
            --build-arg MONGODB_ATLAS_URI=${{ secrets.MONGODB_ATLAS_URI }} \
            --build-arg MONGODB_ATLAS_COLLECTION_NAME=${{ secrets.MONGODB_ATLAS_COLLECTION_NAME }} \
            --build-arg MONGODB_ATLAS_DB_NAME=${{ secrets.MONGODB_ATLAS_DB_NAME }} \
            --build-arg NODE_ENV=${{ secrets.NODE_ENV }} \
            --build-arg GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} \
            --build-arg GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }} \
            --build-arg GITHUB_CLIENT_ID=${{ secrets.GITHUB_CLIENT_ID }} \
            --build-arg GITHUB_CLIENT_SECRET=${{ secrets.GITHUB_CLIENT_SECRET }} \
            --build-arg NEXTAUTH_URL=${{ secrets.NEXTAUTH_URL }} \
            --build-arg NEXTAUTH_SECRET=${{ secrets.NEXTAUTH_SECRET }} \
            --build-arg OLLAMA_BASE_URL=${{ secrets.OLLAMA_BASE_URL }} \
            --build-arg HUGGINGFACE_API_KEY=${{ secrets.HUGGINGFACE_API_KEY }} \
            --build-arg GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }} \
            --build-arg PINECONE_API_KEY=${{ secrets.PINECONE_API_KEY }} \
            --build-arg PINECONE_URL=${{ secrets.PINECONE_URL }} \
            --build-arg MISTRAL_API_KEY=${{ secrets.MISTRAL_API_KEY }}
